blueprint:
  name: Z2M - IKEA E2123 Symfonisk GEN2 remote
  description: Set up custom commands for each button on the Ikea Symfonisk
    Gen 2 Remote. The 2 shortcut buttons also have seperate functions for 
    double press and hold.
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA Symfonisk controller GEN2 to use
      selector:
        device:
          integration: mqtt
          manufacturer: IKEA
          model: SYMFONISK sound remote gen2 (E2123)
          multiple: false
    base_topic:
      name: Zigbee2MQTT Base mqtt topic
      description: The base topic configured in Zigbee2MQTT. If you haven't changed this, leave the default here ("zigbee2mqtt")
      default: zigbee2mqtt
    action_play:
      name: Play button press
      description: Action to run on play button press.
      default: []
      selector:
        action: {}
    action_vol_up:
      name: Volume Up button press
      description: Action to run on volume up button press.
      default: []
      selector:
        action: {}
    action_vol_down:
      name: Volume Down button press
      description: Action to run on volume down button press.
      default: []
      selector:
        action: {}
    action_next:
      name: Next button press
      description: Action to run on next button press.
      default: []
      selector:
        action: {}
    action_previous:
      name: Previous button press
      description: Action to run on previous button press.
      default: []
      selector:
        action: {}
    action_1,1:
      name: Shortcut 1 button press
      description: Action to run on shortcut 1 button single press.
      default: []
      selector:
        action: {}
    action_1,2:
      name: Shortcut 1 button double press
      description: Action to run on shortcut 1 button double press.
      default: []
      selector:
        action: {}
    action_1,3:
      name: Shortcut 1 button hold
      description: Action to run on shortcut 1 button hold.
      default: []
      selector:
        action: {}
    action_2,1:
      name: Shortcut 2 button press
      description: Action to run on shortcut 2 button single press.
      default: []
      selector:
        action: {}
    action_2,2:
      name: Shortcut 2 button double press
      description: Action to run on shortcut 2 button double press.
      default: []
      selector:
        action: {}
    action_2,3:
      name: Shortcut 2 button hold
      description: Action to run on shortcut 2 button hold.
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent

trigger_variables:
  base_topic: !input base_topic
  controller: !input remote

trigger:
  - platform: mqtt
    topic: "{{ base_topic }}/+/action"
action:
- variables:
    controllertopic: "{{ base_topic }}/{{ device_attr(controller, 'name') }}/action"
    # command: '{{ trigger.event.data.command }}'
    # cluster_id: '{{ trigger.event.data.cluster_id }}'
    # endpoint_id: '{{ trigger.event.data.endpoint_id }}'
    # args: '{{ trigger.event.data.args }}'
    action_play: !input action_play
    action_vol_up: !input action_vol_up
    action_vol_down: !input action_vol_down
    action_next: !input action_next
    action_previous: !input action_previous
    action_1,1: !input action_1,1
    action_1,2: !input action_1,2
    action_1,3: !input action_1,3
    action_2,1: !input action_2,1
    action_2,2: !input action_2,2
    action_2,3: !input action_2,3
- choose:
  # Play Button
  - conditions: 
    - "{{ trigger.payload == 'play_pause' }}"
    - "{{ trigger.payload != ''}}"
    - "{{ trigger.topic == controllertopic }}"
    sequence: !input action_play
  - conditions:
    - '{{ command == ''step'' }}'
    - '{{ cluster_id == 8 }}'
    - '{{ endpoint_id == 1 }}'
    - '{{ trigger.event.data.params.step_mode == 0 }}'
    sequence: !input action_next
  - conditions:
    - '{{ command == ''step'' }}'
    - '{{ cluster_id == 8 }}'
    - '{{ endpoint_id == 1 }}'
    - '{{ trigger.event.data.params.step_mode == 1 }}'
    sequence: !input action_previous
  - conditions:
    - '{{ command == ''move_with_on_off'' }}'
    - '{{ cluster_id == 8 }}'
    - '{{ endpoint_id == 1 }}'
    - '{{ trigger.event.data.params.move_mode == 0}}'
    sequence: !input action_vol_up
  - conditions:
    - '{{ command == ''move_with_on_off'' }}'
    - '{{ cluster_id == 8 }}'
    - '{{ endpoint_id == 1 }}'
    - '{{ trigger.event.data.params.move_mode == 1 }}'
    sequence: !input action_vol_down
  - conditions:
    - '{{ command == ''shortcut_v1_events'' }}'
    - '{{ trigger.event.data.args == [1, 1] }}'
    sequence: !input action_1,1
  - conditions:
    - '{{ command == ''shortcut_v1_events'' }}'
    - '{{ trigger.event.data.args == [1, 2] }}'
    sequence: !input action_1,2
  - conditions:
    - '{{ command == ''shortcut_v1_events'' }}'
    - '{{ trigger.event.data.args == [1, 3] }}'
    sequence: !input action_1,3
  - conditions:
    - '{{ command == ''shortcut_v1_events'' }}'
    - '{{ trigger.event.data.args == [2, 1] }}'
    sequence: !input action_2,1
  - conditions:
    - '{{ command == ''shortcut_v1_events'' }}'
    - '{{ trigger.event.data.args == [2, 2] }}'
    sequence: !input action_2,2
  - conditions:
    - '{{ command == ''shortcut_v1_events'' }}'
    - '{{ trigger.event.data.args == [2, 3] }}'
    sequence: !input action_2,3
