blueprint:
  name: Z2M - IKEA E2123 Symfonisk GEN2 remote
  description: Set up custom commands for each button on the Ikea Symfonisk
    Gen 2 Remote. The 2 shortcut buttons also have seperate functions for 
    double press and hold.
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA Symfonisk controller GEN2 to use
      selector:
        device:
          integration: mqtt
          manufacturer: IKEA
          model: SYMFONISK sound remote gen2 (E2123)
          multiple: false
    base_topic:
      name: Zigbee2MQTT Base mqtt topic
      description: The base topic configured in Zigbee2MQTT. If you haven't changed this, leave the default here ("zigbee2mqtt")
      default: zigbee2mqtt
    delay_long:
      name: Long click delay in seconds
      description: The time in seconds (can contain decimals) used as a delay for
        the long click detection
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 10.0
          unit_of_measurement: seconds
          mode: slider
          step: 0.1
    action_play:
      name: Play button press
      description: Action to run on play button press.
      default: []
      selector:
        action: {}
    action_vol_up:
      name: Volume Up button press
      description: Action to run on volume up button press.
      default: []
      selector:
        action: {}
    action_vol_down:
      name: Volume Down button press
      description: Action to run on volume down button press.
      default: []
      selector:
        action: {}
    action_next:
      name: Next button press
      description: Action to run on next button press.
      default: []
      selector:
        action: {}
    action_previous:
      name: Previous button press
      description: Action to run on previous button press.
      default: []
      selector:
        action: {}
    action_dot1:
      name: dot button press
      description: Action to run on dot button press.
      default: []
      selector:
        action: {}
    action_dot2:
      name: two dot button press
      description: Action to run on dot2 button press.
      default: []
      selector:
        action: {}
    # Long press
    single_dot_long_press:
      name: Single Dot (Long)
      description: Action to run on single dot long press
      default: []
      selector: 
        action: {}
    two_dots_long_press:
      name: Two Dot (Long)
      description: Action to run on two dot long press
      default: []
      selector: 
        action: {}
    # Hold press
    volume_up_hold_press:
      name: Volume Up (Long)
      description: Action to run on volume up long press
      default: []
      selector: 
        action: {}
    volume_down_hold_press:
      name: Volume Down (Long)
      description: Action to run on volume Down long press
      default: []
      selector: 
        action: {}
    # Double press
    dots_1_double_press:
      name: dot button double press
      description: Action to run on dot button double press.
      default: []
      selector:
        action: {}
    dots_2_double_press:
      name: two dot button double press
      description: Action to run on two dot button double press.
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent

trigger_variables:
  base_topic: !input base_topic
  controller: !input remote

trigger:
  - platform: mqtt
    topic: "{{ base_topic }}/+/action"
action:
- variables:
    controllertopic: "{{ base_topic }}/{{ device_attr(controller, 'name') }}/action"
    action_play: !input action_play
    action_vol_up: !input action_vol_up
    action_vol_down: !input action_vol_down
    action_next: !input action_next
    action_previous: !input action_previous
    action_dot1: !input action_dot1
    action_dot2: !input action_dot2
- choose:
  - conditions:
      - "{{ trigger.payload != ''}}"
      - "{{ trigger.topic == controllertopic }}"
    sequence:
      - choose:
        # Play Button
        - conditions: 
          - "{{ trigger.payload == 'play_pause' }}"
          sequence: !input action_play
        # Volume Up Button
        - conditions:
          - "{{ trigger.payload == 'volume_up' }}"
          sequence: !input action_vol_up
        # Volume Down Button
        - conditions:
          - "{{ trigger.payload == 'volume_down' }}"
          sequence: !input action_vol_down
        # Next Button
        - conditions:
          - "{{ trigger.payload == 'track_next' }}"
          sequence: !input action_next
        # Previous Button
        - conditions:
          - "{{ trigger.payload == 'track_previous' }}"
          sequence: !input action_previous
        # Dot Button
        - conditions:
          - "{{ trigger.payload == 'dots_1_initial_press' }}"
          sequence: !input action_dot1
        # Two Dot Button
        - conditions:
          - "{{ trigger.payload == 'dots_2_initial_press' }}"
          sequence: !input action_dot2
        # Single Dot Long Press
        - conditions: 
          - "{{ trigger.payload == 'dots_1_long_press' }}"
          sequence: !input single_dot_long_press
        # Two Dot Long Press
        - conditions: 
          - "{{ trigger.payload == 'dots_2_long_press' }}"
          sequence:
          - wait_template: '{{ is_state(switch_id, ''dots_2_long_release'') }}'
            timeout: !input delay_multi
          - choose:
            sequence: !input two_dots_long_press


          

        # Volume Up Long Press
        - conditions: 
          - "{{ trigger.payload == 'volume_up_hold' }}"
          sequence: !input volume_up_hold_press
        # Volume Down Long Press
        - conditions: 
          - "{{ trigger.payload == 'volume_down_hold' }}"
          sequence: !input volume_down_hold_press
        # Dot Button Double Press
        - conditions:
          - "{{ trigger.payload == 'dots_1_double_press' }}"
          sequence: !input dots_1_double_press
        # Two Dot Button Double Press
        - conditions:
          - "{{ trigger.payload == 'dots_2_double_press' }}"
          sequence: !input dots_2_double_press
