blueprint:
  name: Z2M - IKEA E2123 Symfonisk GEN2 remote
  description: Set up custom commands for each button on the Ikea Symfonisk
    Gen 2 Remote. The 2 shortcut buttons also have seperate functions for 
    double press and hold.
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA Symfonisk controller GEN2 to use
      selector:
        device:
          integration: mqtt
          manufacturer: IKEA
          model: SYMFONISK sound remote gen2 (E2123)
          multiple: false
    base_topic:
      name: Zigbee2MQTT Base mqtt topic
      description: The base topic configured in Zigbee2MQTT. If you haven't changed this, leave the default here ("zigbee2mqtt")
      default: zigbee2mqtt
    action_play:
      name: Play button press
      description: Action to run on play button press.
      default: []
      selector:
        action: {}
    action_vol_up:
      name: Volume Up button press
      description: Action to run on volume up button press.
      default: []
      selector:
        action: {}
    action_vol_down:
      name: Volume Down button press
      description: Action to run on volume down button press.
      default: []
      selector:
        action: {}
    action_next:
      name: Next button press
      description: Action to run on next button press.
      default: []
      selector:
        action: {}
    action_previous:
      name: Previous button press
      description: Action to run on previous button press.
      default: []
      selector:
        action: {}
    action_dot1:
      name: dot button press
      description: Action to run on dot button press.
      default: []
      selector:
        action: {}
    action_dot2:
      name: two dot button press
      description: Action to run on dot2 button press.
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent

trigger_variables:
  base_topic: !input base_topic
  controller: !input remote

trigger:
  - platform: mqtt
    topic: "{{ base_topic }}/+/action"
action:
- variables:
    controllertopic: "{{ base_topic }}/{{ device_attr(controller, 'name') }}/action"
    action_play: !input action_play
    action_vol_up: !input action_vol_up
    action_vol_down: !input action_vol_down
    action_next: !input action_next
    action_previous: !input action_previous
    action_dot1: !input action_dot1
    action_dot2: !input action_dot2
- choose:
  # Play Button
  - conditions: 
    - "{{ trigger.payload == 'play_pause' }}"
    - "{{ trigger.payload != ''}}"
    - "{{ trigger.topic == controllertopic }}"
    sequence: !input action_play
  # Volume Up Button
  - conditions:
    - "{{ trigger.payload == 'volume_up' }}"
    - "{{ trigger.payload != ''}}"
    - "{{ trigger.topic == controllertopic }}"
    sequence: !input action_vol_up
  # Volume Down Button
  - conditions:
    - "{{ trigger.payload == 'volume_down' }}"
    - "{{ trigger.payload != ''}}"
    - "{{ trigger.topic == controllertopic }}"
    sequence: !input action_vol_down
  # Next Button
  - conditions:
    - "{{ trigger.payload == 'track_next' }}"
    - "{{ trigger.payload != ''}}"
    - "{{ trigger.topic == controllertopic }}"
    sequence: !input action_next
  # Previous Button
  - conditions:
    - "{{ trigger.payload == 'track_previous' }}"
    - "{{ trigger.payload != ''}}"
    - "{{ trigger.topic == controllertopic }}"
    sequence: !input action_previous
  # Dot Button
  - conditions:
    - "{{ trigger.payload == 'dots_1_initial_press' }}"
    - "{{ trigger.payload != ''}}"
    - "{{ trigger.topic == controllertopic }}"
    sequence: !input action_dot1
  # Two Dot Button
  - conditions:
    - "{{ trigger.payload == 'dots_2_initial_press' }}"
    - "{{ trigger.payload != ''}}"
    - "{{ trigger.topic == controllertopic }}"
    sequence: !input action_dot2
